#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Wrap a framework's hand-rolled unit tests in XCTest (Phase 2 / Stream 7).
#
# Usage:  ruby ide/gen_xctest.rb <framework> <out-dir> <test-file>...
#         prints the generated files, one SRCROOT-relative path per line.
#
# The tests in Frameworks/*/tests/*.{cc,mm} are plain free functions —
# `void test_foo ()` asserting with OAK_ASSERT* — feeding the CLI runner that
# bin/gen_test synthesizes. The original build system invoked it; rave replaced
# that system in 2021 and never carried the rule over, so nothing has invoked it
# since (see PROJECT_PHASES.md, Stream 7). This emits the same test bodies as a
# real XCTest bundle instead, so they run under `xcodebuild test` and Xcode's Test
# navigator.
#
# The file-processing half is deliberately identical to bin/gen_test: hoist the
# #include/#import lines to file scope (a #include cannot appear inside a
# namespace), rewrite quoted includes to absolute paths (test-local helpers like
# parse/tests/support.h), wrap the remaining body in `namespace <basename>` so
# same-named helpers in sibling test files don't collide, and emit #line
# directives throughout. The #line rewriting is load-bearing beyond error
# messages: several tests locate their fixtures with path::join(__FILE__, "..")
# (e.g. network/tests/t_download.cc), which only resolves if __FILE__ still points
# at the original source.
#
# Output is two files: an _impl.mm holding every test body, and a .mm holding only
# the XCTestCase subclasses, which reach the bodies through forward declarations.
#
# Everything compiles as Objective-C++ with ARC off (see CLANG_ENABLE_OBJC_ARC in
# ide/seed_xcodeproj.rb) — the one combination that satisfies both directions these
# tests pull in. Some .cc tests include Objective-C headers (ns/tests/t_*.cc reaches
# <ns/event.h>, which is NSEvent/NSAttributedString), so plain C++ will not compile
# them; and some reach headers ARC rejects (settings/src/track_paths.h calls
# dispatch_release, which under ARC expands to an outlawed [_o release]). None of
# the test files use ARC-only spellings (__bridge/__strong/__weak), so turning ARC
# off costs nothing but leaks in a short-lived test process.

require "fileutils"

# Scan test sources as UTF-8 regardless of the shell's locale (see the note in
# seed_xcodeproj.rb) so a non-ASCII byte in a test file can't crash the scan.
Encoding.default_external = Encoding::UTF_8

ROOT     = File.expand_path("..", __dir__)
PREAMBLE = File.join(__dir__, "xctest_preamble.h")

framework, outdir, *files = ARGV
if framework.nil? || outdir.nil? || files.empty?
  abort "usage: #{$PROGRAM_NAME} <framework> <out-dir> <test-file>..."
end

# Matches bin/gen_test's discovery regexes, with the space before () made optional.
TEST_RE  = /^\s*void\s+(test_\w+)\s*\(\s*\)/.freeze
SETUP_RE = /^\s*void\s+(setup(?:_\w+)?)\s*\(\s*\)/.freeze

# An ObjC class name shares one flat namespace per loaded bundle, so qualify with
# the framework; sanitize since a path basename may hold characters ObjC won't.
def objc_ident(str)
  str.gsub(/[^A-Za-z0-9_]/, "_")
end

suites = []
bodies = +""

files.each do |file|
  path = File.expand_path(file, ROOT)
  ns   = File.basename(path).sub(/\.[^.]+$/, "")
  lineno, includes, lines, tests, setups = 1, [], [], [], []

  File.foreach(path) do |line|
    if line =~ /^\s*#(include|import)\b/
      includes << %(#line #{lineno} "#{path}"\n)
      # Quoted includes are relative to the test file, which is no longer where
      # this code lives — make them absolute.
      includes << line.sub(/"(.*?)"/) { '"' + File.expand_path($1, File.dirname(path)) + '"' }
    else
      lines << %(#line #{lineno} "#{path}"\n)
      lines << line
      tests  << $1 if line =~ TEST_RE
      setups << $1 if line =~ SETUP_RE
    end
    lineno += 1
  end

  bodies << includes.join
  bodies << "namespace #{ns} {\n" << lines.join << "} /* #{ns} */\n\n"

  suites << { ns: ns, klass: objc_ident("#{framework}_#{ns}Tests"), tests: tests, setups: setups }
end

FileUtils.mkdir_p(File.join(ROOT, outdir))
written = []

def write(rel, text, written)
  File.write(File.join(ROOT, rel), text)
  written << rel
end

banner = "// GENERATED by ide/gen_xctest.rb — do not edit. Regenerate via ide/seed_xcodeproj.rb.\n" \
         "// Framework: #{framework}\n"

write("#{outdir}/#{framework}Tests_impl.mm", +"#{banner}#include \"#{PREAMBLE}\"\n\n#{bodies}", written)

# --- the XCTestCase shim ----------------------------------------------------
shim = +"#{banner}#import <XCTest/XCTest.h>\n#include <exception>\n#include <string>\n\n"

suites.each do |s|
  next if s[:tests].empty? && s[:setups].empty?
  shim << "namespace #{s[:ns]} {\n"
  (s[:setups] + s[:tests]).each { |fn| shim << "\tvoid #{fn} ();\n" }
  shim << "}\n\n"
end

suites.each do |s|
  k = s[:klass]

  shim << "@interface #{k} : XCTestCase\n@end\n\n"

  # A thrown oak_exception carries "file:line: message" from OAK_ASSERT*; surface
  # it through XCTFail so Xcode reports a normal test failure instead of the
  # process dying the way bin/gen_test's runner did.
  if s[:setups].empty?
    shim << "@implementation #{k}\n\n"
  else
    # gen_test ran every setup once, up front, before dispatching any test. +setUp
    # is the XCTest equivalent (once per class), but it cannot XCTFail — that needs
    # a test-case instance — so stash the error and report it from -setUp.
    shim << "static std::string #{k}_setupError;\n\n"
    shim << "@implementation #{k}\n\n"
    shim << "+ (void)setUp\n{\n\ttry {\n"
    s[:setups].each { |fn| shim << "\t\t#{s[:ns]}::#{fn}();\n" }
    shim << "\t}\n\tcatch(std::exception const& e) {\n\t\t#{k}_setupError = e.what();\n\t}\n}\n\n"
    shim << "- (void)setUp\n{\n\tif(!#{k}_setupError.empty())\n"
    shim << "\t\tXCTFail(@\"setup failed: %s\", #{k}_setupError.c_str());\n}\n\n"
  end

  s[:tests].each do |fn|
    shim << "- (void)#{fn}\n{\n\ttry {\n\t\t#{s[:ns]}::#{fn}();\n\t}\n"
    shim << "\tcatch(std::exception const& e) {\n\t\tXCTFail(@\"%s\", e.what());\n\t}\n}\n\n"
  end

  shim << "@end\n\n"
end

write("#{outdir}/#{framework}Tests.mm", shim, written)

puts written
