import Foundation
import CryptoKit
import os

// DSA signature verification, written out by hand, because Apple's modern key
// API has none: `SecKeyVerifySignature` supports RSA and ECDSA only, and the
// `SecTransform` family this replaces has been deprecated since macOS 12 and
// documented as "no longer supported" since 13.
//
// **What needs it.** MacroMates' bundle index at api.textmate.org is signed
// with DSA/SHA-1 — measured on the live response, whose `x-amz-meta-x-signature`
// header verifies under `org.textmate.duff` with `openssl dgst -sha1` and under
// nothing else. The two keys that index ships with are 1024-bit (q = 160) and
// 2048-bit (q = 160). Neither the algorithm nor the keys are this fork's to
// change while it fetches that index, so the choice was: keep calling an API
// Apple has announced the end of, or verify the signature here. This file is
// the second choice, and it exists so that the day SecTransform stops being
// linkable is not the day bundle updates silently stop being checked.
//
// **Verification only.** There is no signing here and there should never be:
// signing needs a secret and a source of randomness that must not be got wrong,
// and nothing in this application signs anything with DSA. Verification reads
// only public values, so none of it is secret-dependent and none of it needs to
// be constant-time.
//
// **This is not a general big-integer library.** `DSABigUInt` is unsigned,
// has no negative numbers, no general modular inverse (Fermat's little theorem
// covers the one inverse DSA needs, because q is prime), and is sized for
// numbers of a few thousand bits. It is here rather than in `text` or `oak`
// because nothing else in the tree wants it, and a type this sharp-edged is
// better kept next to its one caller.
//
// The arithmetic is pinned by t_dsa_verifier.mm against openssl: keys and
// signatures generated by `openssl dsaparam`/`gendsa`/`dgst -sha1 -sign`, in
// both shapes the bundle index uses, plus every way a signature can be wrong.

private let log = Logger(subsystem: "com.j23software.TextMate-NG", category: "dsa")

// ==========================================================================
// = DSABigUInt — an unsigned big integer, in base 2^32                     =
// ==========================================================================

struct DSABigUInt {
	// Little-endian, no trailing zero limbs; zero is the empty array. Keeping
	// that invariant is what makes `compare` able to look at the count first.
	private(set) var limbs: [UInt32]

	init() {
		limbs = []
	}

	init(_ value: UInt32) {
		limbs = value == 0 ? [] : [ value ]
	}

	private init(normalizing limbs: [UInt32]) {
		var l = limbs
		while let last = l.last, last == 0 {
			l.removeLast()
		}
		self.limbs = l
	}

	init(bigEndianBytes bytes: [UInt8]) {
		var l: [UInt32] = []
		l.reserveCapacity((bytes.count + 3) / 4)
		var end = bytes.count
		while end > 0 {
			let start = max(0, end - 4)
			var limb: UInt32 = 0
			for byte in bytes[start..<end] {
				limb = (limb << 8) | UInt32(byte)
			}
			l.append(limb)
			end = start
		}
		self.init(normalizing: l)
	}

	var isZero: Bool {
		return limbs.isEmpty
	}

	// Big-endian, minimal length; zero is one 0x00 byte. Only the tests need
	// this — verification never turns a number back into bytes.
	var bigEndianBytes: [UInt8] {
		guard !limbs.isEmpty else { return [ 0 ] }
		var bytes: [UInt8] = []
		bytes.reserveCapacity(limbs.count * 4)
		var i = limbs.count - 1
		while i >= 0 {
			let limb = limbs[i]
			bytes.append(UInt8(truncatingIfNeeded: limb >> 24))
			bytes.append(UInt8(truncatingIfNeeded: limb >> 16))
			bytes.append(UInt8(truncatingIfNeeded: limb >> 8))
			bytes.append(UInt8(truncatingIfNeeded: limb))
			i -= 1
		}
		while bytes.count > 1 && bytes[0] == 0 {
			bytes.removeFirst()
		}
		return bytes
	}

	var bitWidth: Int {
		guard let top = limbs.last else { return 0 }
		return (limbs.count - 1) * 32 + (32 - top.leadingZeroBitCount)
	}

	func bit(at index: Int) -> Bool {
		let limb = index / 32
		guard limb < limbs.count else { return false }
		return (limbs[limb] >> UInt32(index % 32)) & 1 == 1
	}

	static func compare(_ lhs: DSABigUInt, _ rhs: DSABigUInt) -> Int {
		if lhs.limbs.count != rhs.limbs.count {
			return lhs.limbs.count < rhs.limbs.count ? -1 : 1
		}
		var i = lhs.limbs.count - 1
		while i >= 0 {
			if lhs.limbs[i] != rhs.limbs[i] {
				return lhs.limbs[i] < rhs.limbs[i] ? -1 : 1
			}
			i -= 1
		}
		return 0
	}

	static func == (lhs: DSABigUInt, rhs: DSABigUInt) -> Bool { compare(lhs, rhs) == 0 }
	static func <  (lhs: DSABigUInt, rhs: DSABigUInt) -> Bool { compare(lhs, rhs) <  0 }

	static func + (lhs: DSABigUInt, rhs: DSABigUInt) -> DSABigUInt {
		let count = max(lhs.limbs.count, rhs.limbs.count)
		var res: [UInt32] = []
		res.reserveCapacity(count + 1)
		var carry: UInt64 = 0
		for i in 0..<count {
			let sum = UInt64(i < lhs.limbs.count ? lhs.limbs[i] : 0)
			        + UInt64(i < rhs.limbs.count ? rhs.limbs[i] : 0)
			        + carry
			res.append(UInt32(truncatingIfNeeded: sum))
			carry = sum >> 32
		}
		if carry != 0 {
			res.append(UInt32(carry))
		}
		return DSABigUInt(normalizing: res)
	}

	// Requires lhs >= rhs; the caller checks, because every subtraction here
	// follows a comparison that already established it.
	static func - (lhs: DSABigUInt, rhs: DSABigUInt) -> DSABigUInt {
		var res: [UInt32] = []
		res.reserveCapacity(lhs.limbs.count)
		var borrow: Int64 = 0
		for i in 0..<lhs.limbs.count {
			let difference = Int64(lhs.limbs[i]) - Int64(i < rhs.limbs.count ? rhs.limbs[i] : 0) - borrow
			if difference < 0 {
				res.append(UInt32(truncatingIfNeeded: difference + 0x1_0000_0000))
				borrow = 1
			} else {
				res.append(UInt32(difference))
				borrow = 0
			}
		}
		return DSABigUInt(normalizing: res)
	}

	static func * (lhs: DSABigUInt, rhs: DSABigUInt) -> DSABigUInt {
		if lhs.isZero || rhs.isZero {
			return DSABigUInt()
		}
		var res = [UInt32](repeating: 0, count: lhs.limbs.count + rhs.limbs.count)
		for i in 0..<lhs.limbs.count {
			let a = UInt64(lhs.limbs[i])
			var carry: UInt64 = 0
			for j in 0..<rhs.limbs.count {
				// a*b + res + carry ≤ (2³²-1)² + 2(2³²-1) = 2⁶⁴-1, so this never wraps.
				let t = a * UInt64(rhs.limbs[j]) + UInt64(res[i + j]) + carry
				res[i + j] = UInt32(truncatingIfNeeded: t)
				carry = t >> 32
			}
			var k = i + rhs.limbs.count
			while carry != 0 {
				let t = UInt64(res[k]) + carry
				res[k] = UInt32(truncatingIfNeeded: t)
				carry = t >> 32
				k += 1
			}
		}
		return DSABigUInt(normalizing: res)
	}

	// Knuth's algorithm D (TAOCP 4.3.1), with the single-limb divisor as its own
	// path because D needs at least two limbs to estimate from.
	static func divMod(_ dividend: DSABigUInt, _ divisor: DSABigUInt) -> (quotient: DSABigUInt, remainder: DSABigUInt) {
		precondition(!divisor.isZero, "DSABigUInt: division by zero")

		if compare(dividend, divisor) < 0 {
			return (DSABigUInt(), dividend)
		}

		if divisor.limbs.count == 1 {
			let d = UInt64(divisor.limbs[0])
			var quotient = [UInt32](repeating: 0, count: dividend.limbs.count)
			var remainder: UInt64 = 0
			var i = dividend.limbs.count - 1
			while i >= 0 {
				let current = (remainder << 32) | UInt64(dividend.limbs[i])
				quotient[i] = UInt32(current / d)
				remainder = current % d
				i -= 1
			}
			return (DSABigUInt(normalizing: quotient), DSABigUInt(UInt32(remainder)))
		}

		let n = divisor.limbs.count
		let m = dividend.limbs.count - n

		// Normalise so the divisor's top limb has its high bit set, which is what
		// bounds the quotient estimate below to at most two too large.
		let shift = Int(divisor.limbs[n - 1].leadingZeroBitCount)
		let v = shiftedLeft(divisor.limbs, by: shift, count: n)
		var u = shiftedLeft(dividend.limbs, by: shift, count: dividend.limbs.count + 1)

		var quotient = [UInt32](repeating: 0, count: m + 1)
		let base: UInt64 = 1 << 32

		var j = m
		while j >= 0 {
			let top = (UInt64(u[j + n]) << 32) | UInt64(u[j + n - 1])
			var qhat = top / UInt64(v[n - 1])
			var rhat = top % UInt64(v[n - 1])

			// `qhat >= base` is tested first and short-circuits: only once it is
			// false does `qhat * v[n-2]` fit in 64 bits.
			while qhat >= base || qhat * UInt64(v[n - 2]) > (rhat << 32) + UInt64(u[j + n - 2]) {
				qhat -= 1
				rhat += UInt64(v[n - 1])
				if rhat >= base {
					break
				}
			}

			// Multiply and subtract.
			var borrow: Int64 = 0
			var carry: UInt64 = 0
			for i in 0..<n {
				let product = qhat * UInt64(v[i]) + carry
				carry = product >> 32
				let difference = Int64(u[i + j]) - Int64(product & 0xFFFF_FFFF) - borrow
				if difference < 0 {
					u[i + j] = UInt32(truncatingIfNeeded: difference + Int64(base))
					borrow = 1
				} else {
					u[i + j] = UInt32(difference)
					borrow = 0
				}
			}
			let topDifference = Int64(u[j + n]) - Int64(carry) - borrow
			if topDifference < 0 {
				// The estimate was one too large — the case Knuth measures as
				// happening about twice in 2³², and the reason this branch is here
				// rather than assumed away.
				u[j + n] = UInt32(truncatingIfNeeded: topDifference + Int64(base))
				qhat -= 1
				var addCarry: UInt64 = 0
				for i in 0..<n {
					let t = UInt64(u[i + j]) + UInt64(v[i]) + addCarry
					u[i + j] = UInt32(truncatingIfNeeded: t)
					addCarry = t >> 32
				}
				u[j + n] = UInt32(truncatingIfNeeded: UInt64(u[j + n]) &+ addCarry)
			} else {
				u[j + n] = UInt32(topDifference)
			}

			quotient[j] = UInt32(truncatingIfNeeded: qhat)
			j -= 1
		}

		let remainder = shiftedRight(Array(u[0..<n]), by: shift)
		return (DSABigUInt(normalizing: quotient), DSABigUInt(normalizing: remainder))
	}

	static func % (lhs: DSABigUInt, rhs: DSABigUInt) -> DSABigUInt {
		return divMod(lhs, rhs).remainder
	}

	static func modPow(_ base: DSABigUInt, _ exponent: DSABigUInt, _ modulus: DSABigUInt) -> DSABigUInt {
		if modulus.isZero {
			return DSABigUInt()
		}
		var result = DSABigUInt(1) % modulus
		let b = base % modulus
		var i = exponent.bitWidth - 1
		while i >= 0 {
			result = (result * result) % modulus
			if exponent.bit(at: i) {
				result = (result * b) % modulus
			}
			i -= 1
		}
		return result
	}

	// The one inverse DSA needs, by Fermat: q is prime, so s⁻¹ ≡ s^(q-2) (mod q).
	// An extended-Euclid inverse would need signed arithmetic this type does not
	// have, for no gain — and if q were somehow not prime the result would simply
	// be a wrong `w`, which fails the verification rather than passing it.
	static func modInverse(_ value: DSABigUInt, primeModulus q: DSABigUInt) -> DSABigUInt {
		return modPow(value, q - DSABigUInt(2), q)
	}

	private static func shiftedLeft(_ x: [UInt32], by shift: Int, count: Int) -> [UInt32] {
		var res = [UInt32](repeating: 0, count: count)
		if shift == 0 {
			for i in 0..<min(x.count, count) {
				res[i] = x[i]
			}
			return res
		}
		var carry: UInt32 = 0
		for i in 0..<min(x.count, count) {
			res[i] = (x[i] << UInt32(shift)) | carry
			carry = x[i] >> UInt32(32 - shift)
		}
		if x.count < count {
			res[x.count] = carry
		}
		return res
	}

	private static func shiftedRight(_ x: [UInt32], by shift: Int) -> [UInt32] {
		if shift == 0 {
			return x
		}
		var res = [UInt32](repeating: 0, count: x.count)
		var carry: UInt32 = 0
		var i = x.count - 1
		while i >= 0 {
			res[i] = (x[i] >> UInt32(shift)) | carry
			carry = x[i] << UInt32(32 - shift)
			i -= 1
		}
		return res
	}
}

// ==========================================================================
// = A DER reader, just enough for a public key and a signature             =
// ==========================================================================

// Every read is bounds-checked and returns nil rather than trapping: the
// signature arrives in an HTTP header, so malformed input is an expected case
// and must be a refusal, not a crash (rule 33 in the small).
private struct DERReader {
	private let bytes: [UInt8]
	private var position: Int

	init(_ bytes: [UInt8]) {
		self.bytes = bytes
		self.position = 0
	}

	var isAtEnd: Bool {
		return position >= bytes.count
	}

	mutating func readValue(tag expected: UInt8) -> [UInt8]? {
		guard position < bytes.count, bytes[position] == expected else { return nil }
		position += 1

		guard position < bytes.count else { return nil }
		let first = bytes[position]
		position += 1

		var length = 0
		if first & 0x80 == 0 {
			length = Int(first)
		} else {
			let byteCount = Int(first & 0x7F)
			// 0 is the indefinite-length form, which DER forbids; more than four
			// length bytes would describe something far larger than any key.
			guard byteCount > 0, byteCount <= 4, position + byteCount <= bytes.count else { return nil }
			for _ in 0..<byteCount {
				length = (length << 8) | Int(bytes[position])
				position += 1
			}
		}

		guard length >= 0, position + length <= bytes.count else { return nil }
		let value = Array(bytes[position..<(position + length)])
		position += length
		return value
	}

	mutating func readInteger() -> DSABigUInt? {
		guard let content = readValue(tag: 0x02), let first = content.first else { return nil }
		// A set high bit means a negative number in DER; every value in a DSA key
		// or signature is positive, so that is malformed rather than large.
		guard first & 0x80 == 0 else { return nil }
		return DSABigUInt(bigEndianBytes: content)
	}
}

// ==========================================================================
// = OakDSAVerifier                                                         =
// ==========================================================================

@objc(OakDSAVerifier)
final class OakDSAVerifier: NSObject {
	struct PublicKey {
		let p: DSABigUInt
		let q: DSABigUInt
		let g: DSABigUInt
		let y: DSABigUInt
	}

	// id-dsa, 1.2.840.10040.4.1. Checked rather than assumed: an RSA key in the
	// same PEM shape would otherwise be read as three integers that happen to
	// parse.
	private static let dsaOID: [UInt8] = [ 0x2A, 0x86, 0x48, 0xCE, 0x38, 0x04, 0x01 ]

	static func derBytes(fromPEM pem: String) -> [UInt8]? {
		var body = ""
		var inside = false
		for line in pem.split(whereSeparator: \.isNewline) {
			let trimmed = line.trimmingCharacters(in: .whitespaces)
			if trimmed.hasPrefix("-----BEGIN") {
				inside = true
			} else if trimmed.hasPrefix("-----END") {
				inside = false
			} else if inside {
				body += trimmed
			}
		}
		guard !body.isEmpty, let data = Data(base64Encoded: body, options: [ .ignoreUnknownCharacters ]) else { return nil }
		return [UInt8](data)
	}

	// SubjectPublicKeyInfo:
	//   SEQUENCE { SEQUENCE { OID id-dsa, SEQUENCE { p, q, g } }, BIT STRING { INTEGER y } }
	static func publicKey(fromPEM pem: String) -> PublicKey? {
		guard let der = derBytes(fromPEM: pem) else { return nil }

		var outer = DERReader(der)
		guard let info = outer.readValue(tag: 0x30) else { return nil }

		var infoReader = DERReader(info)
		guard let algorithm = infoReader.readValue(tag: 0x30) else { return nil }

		var algorithmReader = DERReader(algorithm)
		guard let oid = algorithmReader.readValue(tag: 0x06), oid == dsaOID else { return nil }
		guard let parameters = algorithmReader.readValue(tag: 0x30) else { return nil }

		var parameterReader = DERReader(parameters)
		guard let p = parameterReader.readInteger(),
		      let q = parameterReader.readInteger(),
		      let g = parameterReader.readInteger(),
		      parameterReader.isAtEnd
		else { return nil }

		guard let bitString = infoReader.readValue(tag: 0x03), let unusedBits = bitString.first, unusedBits == 0 else { return nil }

		var keyReader = DERReader(Array(bitString.dropFirst()))
		guard let y = keyReader.readInteger(), keyReader.isAtEnd else { return nil }

		guard !p.isZero, !q.isZero, !g.isZero else { return nil }
		return PublicKey(p: p, q: q, g: g, y: y)
	}

	// Dss-Sig-Value: SEQUENCE { INTEGER r, INTEGER s }
	static func signature(fromDER der: [UInt8]) -> (r: DSABigUInt, s: DSABigUInt)? {
		var outer = DERReader(der)
		guard let body = outer.readValue(tag: 0x30) else { return nil }
		var reader = DERReader(body)
		guard let r = reader.readInteger(), let s = reader.readInteger(), reader.isAtEnd else { return nil }
		return (r, s)
	}

	// FIPS 186-4 §4.7. `z` is the leftmost min(N, outlen) bits of the hash; with
	// SHA-1 (160 bits) and the q of every key this verifies (160 or 224 bits)
	// that is the whole digest, but the shift is written out so the function is
	// right rather than right-by-coincidence.
	static func verify(digest: [UInt8], signature: (r: DSABigUInt, s: DSABigUInt), key: PublicKey) -> Bool {
		let r = signature.r
		let s = signature.s

		// 0 < r < q and 0 < s < q. Without this a signature of (0, 0) would send
		// the arithmetic below to v = 0 and compare equal to r.
		guard !r.isZero, !s.isZero, r < key.q, s < key.q else { return false }

		var z = DSABigUInt(bigEndianBytes: digest)
		let excessBits = digest.count * 8 - key.q.bitWidth
		if excessBits > 0 {
			var shifted = z
			for _ in 0..<excessBits {
				shifted = DSABigUInt.divMod(shifted, DSABigUInt(2)).quotient
			}
			z = shifted
		}

		let w  = DSABigUInt.modInverse(s, primeModulus: key.q)
		let u1 = (z * w) % key.q
		let u2 = (r * w) % key.q

		let v = ((DSABigUInt.modPow(key.g, u1, key.p) * DSABigUInt.modPow(key.y, u2, key.p)) % key.p) % key.q
		return v == r
	}

	// Verification from a digest that was computed elsewhere. This exists for
	// t_dsa_verifier.mm, which checks the *live* bundle index's real signature
	// under MacroMates' real key: DSA signs the hash, so the test needs the
	// 288 KB index's SHA-1 rather than the index.
	@objc(verifyDigest:derSignature:pemPublicKey:)
	static func verify(digest: Data, derSignature: Data, pemPublicKey pem: String) -> Bool {
		guard let key = publicKey(fromPEM: pem), let parsed = signature(fromDER: [UInt8](derSignature)) else { return false }
		return verify(digest: [UInt8](digest), signature: parsed, key: key)
	}

	// Division, for the arithmetic tests. Knuth's add-back correction fires about
	// twice in 2³² divisions, so no DSA fixture will ever reach it by chance and
	// t_dsa_verifier.mm drives it here with vectors chosen to force it.
	@objc(divideDividend:byDivisor:)
	static func divide(dividend: Data, by divisor: Data) -> [Data]? {
		let d = DSABigUInt(bigEndianBytes: [UInt8](divisor))
		guard !d.isZero else { return nil }
		let (quotient, remainder) = DSABigUInt.divMod(DSABigUInt(bigEndianBytes: [UInt8](dividend)), d)
		return [ Data(quotient.bigEndianBytes), Data(remainder.bigEndianBytes) ]
	}

	// Multiplication and modular exponentiation, for the same reason.
	@objc(multiply:by:)
	static func multiply(_ lhs: Data, by rhs: Data) -> Data {
		return Data((DSABigUInt(bigEndianBytes: [UInt8](lhs)) * DSABigUInt(bigEndianBytes: [UInt8](rhs))).bigEndianBytes)
	}

	@objc(modPowBase:exponent:modulus:)
	static func modPow(base: Data, exponent: Data, modulus: Data) -> Data {
		return Data(DSABigUInt.modPow(DSABigUInt(bigEndianBytes: [UInt8](base)), DSABigUInt(bigEndianBytes: [UInt8](exponent)), DSABigUInt(bigEndianBytes: [UInt8](modulus))).bigEndianBytes)
	}

	// [p, q, g, y] bit widths, or nil if the PEM is not a DSA public key. For
	// the tests, which pin the parser against the real keys' shapes.
	@objc(publicKeyBitWidthsFromPEM:)
	static func publicKeyBitWidths(fromPEM pem: String) -> [NSNumber]? {
		guard let key = publicKey(fromPEM: pem) else { return nil }
		return [ key.p.bitWidth, key.q.bitWidth, key.g.bitWidth, key.y.bitWidth ].map { NSNumber(value: $0) }
	}

	// The entry point the download manager uses: a PEM public key, a DER
	// signature, and the bytes it covers.
	@objc(verifyData:derSignature:pemPublicKey:)
	static func verify(data: Data, derSignature: Data, pemPublicKey pem: String) -> Bool {
		guard let key = publicKey(fromPEM: pem) else {
			log.error("Not a DSA public key")
			return false
		}
		guard let parsed = signature(fromDER: [UInt8](derSignature)) else {
			log.error("Not a DER DSA signature")
			return false
		}
		let digest = [UInt8](Insecure.SHA1.hash(data: data))
		return verify(digest: digest, signature: parsed, key: key)
	}
}
